/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"

int *
send_message_1_svc(message *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Send message function with params %s %d is called\n", argp->str, argp->length);

	result = 1;

	return &result;
}