/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"


void
send_message_prog_1(char *host, char* c, int len)
{
	CLIENT *clnt;
	int  *result_1;
	message  send_message_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SEND_MESSAGE_PROG, SEND_MESSAGE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	send_message_1_arg.str = c;
	send_message_1_arg.length = len;
	result_1 = send_message_1(&send_message_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	send_message_prog_1 (host, "abcd", 4);
exit (0);
}
