/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"

int send_message_prog_1(char *host, char *file, char *str, int length)
{
	CLIENT *clnt;
	int *result_1;
	message send_message_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, SEND_MESSAGE_PROG, SEND_MESSAGE_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	send_message_1_arg.file = file;
	send_message_1_arg.length = length;
	send_message_1_arg.str = str;
	result_1 = send_message_1(&send_message_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
	return *result_1;
}

int main(int argc, char *argv[])
{
	char *host;
	char *filename;

	if (argc < 4)
	{
		printf("usage: %s server_host filename filename-on-server\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	filename = argv[2];
	char *filename_on_server = argv[3];

	FILE *filetosend = fopen(filename, "r");

	if (filetosend == NULL)
	{
		printf("Failed to open file");
		exit(0);
	}

	int n = 0;
	char *str = malloc(sizeof(char) * 32);
	int c;

	// printf("reached here");
	// fflush(stdout);
	while ((c = fgetc(filetosend)) != EOF)
	{
		// printf("reached here");
		// fflush(stdout);

		str[n++] = (char)c;
		// 	printf("reached here2");
		// fflush(stdout);
		if (n == 32)
		{
			str[n] = '\0';
			int retries = 0;
			while (send_message_prog_1(host, filename_on_server, str, n) == 0)
			{
				retries++;
				if (retries == 5)
				{
					printf("Failed to send file to the server, please try again.");
					exit(0);
				}
			}
			n = 0;
		}
	}

	if (n > 0)
	{
		str[n] = '\0';
		int retries = 0;
		while (send_message_prog_1(host, filename_on_server, str, n) == 0)
		{
			retries++;
			if (retries == 5)
			{
				printf("Failed to send file to the server, please try again.");
				exit(0);
			}
		}
	}

	exit(0);
}
