/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MESSAGE_H_RPCGEN
#define _MESSAGE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char *file;
	char *str;
	int length;
};
typedef struct message message;

#define SEND_MESSAGE_PROG 0x23451111
#define SEND_MESSAGE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_message 1
extern  int * send_message_1(message *, CLIENT *);
extern  int * send_message_1_svc(message *, struct svc_req *);
extern int send_message_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_message 1
extern  int * send_message_1();
extern  int * send_message_1_svc();
extern int send_message_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MESSAGE_H_RPCGEN */
