/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "message.h"

int *send_message_1_svc(message *argp, struct svc_req *rqstp)
{
	static int result;
	int num;

	printf("Send message function with params %s %d is called\n", argp->str, argp->length);

	FILE *output;
	output = fopen(argp->file, "a");

	if (output == NULL)
	{
		result = 0;
		return &result;
	}

	if ((num = fputs(argp->str, output)) != EOF)
		result = 1;
	else
		result = 0;

	fclose(output);

	return &result;
}
